name: edurance_app
description: Edurance.ai Flutter app (V1)
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  flutter_secure_storage: ^10.0.0
  image_picker: ^0.8.7
  flutter_pdfview: ^1.2.3
  provider: ^6.0.5
  url_launcher: ^6.1.7
  flutter_tts: ^3.8.5
  speech_to_text: ^7.3.0
  dio: ^5.9.0


flutter:
  uses-material-design: true